user root;
error_log stderr warn;
pid /tmp/nginx.pid;

worker_processes auto;

events {
    worker_connections 512;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log off;

    client_body_temp_path /tmp/client_body;
    proxy_temp_path       /tmp/proxy;
    fastcgi_temp_path     /tmp/fastcgi;
    uwsgi_temp_path       /tmp/uwsgi;
    scgi_temp_path        /tmp/scgi;

    sendfile on;
    keepalive_timeout 65;

    include /etc/nginx/http.d/*.conf;
}
