#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -euo pipefail
mkdir -p /run/postgresql
# fix-attrs.d/01-postgres-data has already chowned /data/postgres/data to root.
exec env LD_PRELOAD=/usr/local/lib/libfakeeuid.so \
  postgres -D /data/postgres/data
