#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -euo pipefail
mkdir -p /data/redis
exec redis-server \
  --bind 127.0.0.1 \
  --port "${REDIS_PORT}" \
  --dir /data/redis \
  --appendonly no \
  --save 60 1000
